server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/cloud_order?useSSL=false
    username: root
    password: iPad2021
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name:  orderservice
  cloud:
    nacos:
      server-addr: nacos:8848  #nacos的地址
      discovery:
        cluster-name: HZ #集群名称
#        ephemeral: false  #非临时实例
#        namespace: 14663721-1fa6-4b3f-a536-2ce426e99647 #dev环境
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  #负载均衡的规则,集群优先

ribbon:
  eager-load:
    enabled: true   #开启饥饿加载
    clients: orderservice  #饥饿加载的服务名称

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka/

#userservice:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #负载均衡的规则
feign:
  client:
    config:
      default:
        logger-level: basic
  httpclient:
    max-connections: 200  #最大连接数
    max-connections-per-route: 50 #单个路径的最大连接数
    enabled: true #开启feign对httpClient的支持

